package networking;

public enum MessageType {
    NEW_TRANSACTION,
    NEW_BLOCK,
    BLOCKCHAIN_REQUEST,
    BLOCKCHAIN_RESPONSE,
    SHARE_PEER_LIST,
    SYNC_REQUEST,
    SYNC_RESPONSE,
    PEER_DISCOVERY_RESPONSE,
    PEER_DISCOVERY_REQUEST,
    PUBLIC_KEY_EXCHANGE,
    CONNECTION_ESTABLISHED,
    DISCONNECT
}